[package]
name = "Kampfrichtereinsatzpläne"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }
# dotnet-native = { path = "/Users/philippremy/RustroverProjects/dotnet-native" }

[dependencies]
tauri = { version = "1.5", features = [ "dialog-open", "window-set-title", "dialog-ask", "dialog-save", "window-close", "window-create"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
