name: 'Publish Release'

on:
  push:
    branches:
      - production

jobs:
  publish-release:
    environment: Release
    env:
      TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'self-hosted' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'self-hosted' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          # Deactivate Linux builds until further notice; the bundling does not work
          # - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            #  args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81.0

      - name: Install Linux dependencies (apt)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libgtk-3-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: Install Node dependencies (npm)
        run: npm install # change this to npm, pnpm or bun depending on which one you use.

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4

      - name: Load Environment Variables (Release Notes)
        uses: xom9ikk/dotenv@v2
        with:
          path: environment
          mode: production

      - name: Run Tauri Build (Windows & Linux)
        if: matrix.platform != 'self-hosted'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        with:
          tagName: dtb-kampfrichtereinsatzplaene-v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: 'DTB Kampfrichtereinsatzpläne v__VERSION__'
          releaseBody: ${{ env.RELEASE_BODY }}
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}

      - name: Run Tauri Build (macOS)
        if: matrix.platform == 'self-hosted'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        with:
          tauriScript: "npm run tauri-macos"
          tagName: dtb-kampfrichtereinsatzplaene-v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: 'DTB Kampfrichtereinsatzpläne v__VERSION__'
          releaseBody: ${{ env.RELEASE_BODY }}
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}
